/**
 * /!\ THIS CODE SHOULD BE AUTOGENERATED /!\
 * /!\ We don't have a script to do this yet but it is dangerous to do by hand /!\
 * /!\ Right now, each module you wish to asynchronously imported requires this wrapper module /!\
 */
module type FaqIntf = (module type of Faq);

let importable: (module FaqIntf) = (module Faq);
